name: Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install modules
      - name: Install modules
        run: yarn install

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint contracts/interfaces/*.sol contracts/*.sol contracts/test/*.sol

      # Compile the code and run hardhat tests
      - name: Compile the code and run hardhat tests
        run: ./node_modules/.bin/hardhat test

      # Run hardhat coverage
      - name: Solidity coverage
        run: ./node_modules/.bin/hardhat coverage

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.7"
      - run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.10.1/gitleaks_8.10.1_linux_x64.tar.gz && \
          tar -xzf gitleaks_8.10.1_linux_x64.tar.gz && \
          sudo install gitleaks /usr/bin && \
          gitleaks detect --report-format json --report-path leak_report -v